<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find fishbot_description)/urdf/fishbot/common_intertia.urdf.xacro"/>
    <xacro:macro name="base_xacro" params="length radius">
        <link name="base_footPrint"/>
        <!-- 机器人的身体部分 -->
        <link name="base_link">
            <!-- 部件的外观描述 -->
            <visual>
                <!-- 沿着自身几何中心的偏移量和旋转量 -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- 几何形状 -->
                <geometry>
                    <!-- 圆柱体 -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!-- 材质 颜色 -->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </visual>
            <collision>
                <!-- 沿着自身几何中心的偏移量和旋转量 -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- 几何形状 -->
                <geometry>
                    <!-- 圆柱体 -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!-- 材质 颜色 -->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </collision>
            <xacro:cylinder_intertia m="1.0" r="${radius}" h="${length}"/>
        </link>
        <joint name="base_joint" type="fixed">
            <!-- 关节的父部件 -->
            <parent link="base_footPrint"/>
            <!-- 关节的子部件 -->
            <child link="base_link"/>
            <!-- 关节的位置和旋转 -->
            <origin xyz="0.0 0.0 ${length/2+0.032-0.001}" rpy="0.0 0.0 0.0"/>
        </joint>
    </xacro:macro>
</robot>